{% set name = "iota" %}
{% set version = "1.4.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 657476e91d3d16b98eaf723d360547c4911329d065dda256be4e2950cdd11602

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - iota = iota.command_line.iota_gui_launch:entry_point
    - iota.filter_pickles = iota.command_line.iota_filter_pickles:entry_point
    - iota.run = iota.command_line.iota_run:entry_point
    - iota.single_image = iota.command_line.iota_single_image:entry_point
    - iota.track_images = iota.command_line.iota_track_images:entry_point

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - numpy
    - matplotlib-base
    - python >={{ python_min }}
    - six
    - wxpython

test:
  requires:
    - python {{ python_min }}
  imports:
    - iota

about:
  home: https://github.com/ssrl-px/iota
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'IOTA: Integration Optimization, Triage and Analysis'
  description: |
    IOTA is a user-friendly front end for dials.stills_process,
    a serial diffraction data processing program.
  dev_url: https://github.com/ssrl-px/iota

extra:
  recipe-maintainers:
    - ndevenish
    - alyubimov
    - Anthchirp
